// <auto-generated />
using System;
using GESTION_S_E.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GESTION_S_E.Migrations
{
    [DbContext(typeof(MonDbContext))]
    [Migration("20260510013207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GESTION_S_E.Models.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClasse"));

                    b.Property<string>("AnneeAcademique")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("annee_academique");

                    b.Property<int>("Effectif")
                        .HasColumnType("integer")
                        .HasColumnName("Effectif");

                    b.Property<string>("Filiere")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Filiere");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Niveau");

                    b.Property<string>("NomClasse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_classe");

                    b.HasKey("IdClasse");

                    b.ToTable("classes", t =>
                        {
                            t.HasCheckConstraint("CK_Classe_Niveau", "\"Niveau\" IN ('L1','L2','L3','M1','M2')");
                        });
                });

            modelBuilder.Entity("GESTION_S_E.Models.Club", b =>
                {
                    b.Property<int>("IdClub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_club");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClub"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean")
                        .HasColumnName("actif");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("integer")
                        .HasColumnName("id_responsable");

                    b.Property<string>("NomClub")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_club");

                    b.HasKey("IdClub");

                    b.HasIndex("IdResponsable");

                    b.HasIndex("NomClub")
                        .IsUnique();

                    b.ToTable("clubs");
                });

            modelBuilder.Entity("GESTION_S_E.Models.DisponibiliteEnseignant", b =>
                {
                    b.Property<int>("IdDispo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_dispo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDispo"));

                    b.Property<DateTime?>("DateSpecifique")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_specifique");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("integer")
                        .HasColumnName("id_enseignant");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("jour");

                    b.Property<string>("TypeDispo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type_dispo");

                    b.HasKey("IdDispo");

                    b.HasIndex("IdEnseignant");

                    b.ToTable("disponibilites_enseignants", t =>
                        {
                            t.HasCheckConstraint("CK_Dispo_Jour", "jour IN ('Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi')");

                            t.HasCheckConstraint("CK_Dispo_Type", "type_dispo IN ('cours','td','tp','reunion')");
                        });
                });

            modelBuilder.Entity("GESTION_S_E.Models.Eleve", b =>
                {
                    b.Property<int>("IdEleve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_eleve");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEleve"));

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_naissance");

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricule");

                    b.Property<string>("NomEleve")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_eleve");

                    b.Property<string>("PrenomEleve")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom_eleve");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdEleve");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("eleves");
                });

            modelBuilder.Entity("GESTION_S_E.Models.EleveGroupe", b =>
                {
                    b.Property<int>("IdEleve")
                        .HasColumnType("integer")
                        .HasColumnName("id_eleve");

                    b.Property<int>("IdGroupe")
                        .HasColumnType("integer")
                        .HasColumnName("id_groupe");

                    b.HasKey("IdEleve", "IdGroupe");

                    b.HasIndex("IdGroupe");

                    b.ToTable("eleve_groupe");
                });

            modelBuilder.Entity("GESTION_S_E.Models.EmploiDuTemps", b =>
                {
                    b.Property<int>("IdEmploi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_emploi");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmploi"));

                    b.Property<DateTime>("DateCours")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_cours");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin");

                    b.Property<int?>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("integer")
                        .HasColumnName("id_enseignant");

                    b.Property<int?>("IdGroupe")
                        .HasColumnType("integer")
                        .HasColumnName("id_groupe");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<int>("IdSalle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("semestre");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("statut");

                    b.HasKey("IdEmploi");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdGroupe");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdSalle");

                    b.ToTable("emplois_du_temps", t =>
                        {
                            t.HasCheckConstraint("CK_Emploi_Destinataire", "id_classe IS NOT NULL OR id_groupe IS NOT NULL");

                            t.HasCheckConstraint("CK_Emploi_Semestre", "semestre IN ('S1','S2','S3','S4','S5','S6')");

                            t.HasCheckConstraint("CK_Emploi_Statut", "statut IN ('planifie','en_cours','termine','annule','reporte')");
                        });
                });

            modelBuilder.Entity("GESTION_S_E.Models.Enseignant", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_enseignant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnseignant"));

                    b.Property<string>("EmailPro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email_pro");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("NomEnseignant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_enseignant");

                    b.Property<string>("PrenomEnseignant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom_enseignant");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("specialite");

                    b.Property<string>("TelephoneEnseignant")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone_enseignant");

                    b.HasKey("IdEnseignant");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("enseignants");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Groupe", b =>
                {
                    b.Property<int>("IdGroupe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_groupe");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGroupe"));

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<string>("NomGroupe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_groupe");

                    b.HasKey("IdGroupe");

                    b.HasIndex("IdClasse");

                    b.ToTable("groupes");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMatiere"));

                    b.Property<string>("CodeMatiere")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code_matiere");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("coefficient");

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nom_matiere");

                    b.Property<int?>("VolumeHoraire")
                        .HasColumnType("integer")
                        .HasColumnName("volume_horaire");

                    b.HasKey("IdMatiere");

                    b.HasIndex("CodeMatiere")
                        .IsUnique();

                    b.ToTable("matieres");
                });

            modelBuilder.Entity("GESTION_S_E.Models.MatiereClasse", b =>
                {
                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer")
                        .HasColumnName("id_matiere");

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.HasKey("IdMatiere", "IdClasse");

                    b.HasIndex("IdClasse");

                    b.ToTable("matiere_classe");
                });

            modelBuilder.Entity("GESTION_S_E.Models.MembreClub", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("id_club");

                    b.Property<DateTime>("DateAdhesion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_adhesion");

                    b.Property<string>("RoleMembre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role_membre");

                    b.HasKey("IdUtilisateur", "IdClub");

                    b.HasIndex("IdClub");

                    b.ToTable("membres_club", t =>
                        {
                            t.HasCheckConstraint("CK_Membre_Role", "role_membre IN ('president','tresorier','secretaire','membre')");
                        });
                });

            modelBuilder.Entity("GESTION_S_E.Models.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_notification");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotification"));

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_envoi");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<bool>("Lu")
                        .HasColumnType("boolean")
                        .HasColumnName("lu");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("GESTION_S_E.Models.ReservationSalle", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reservation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReservation"));

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_reservation");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval")
                        .HasColumnName("heure_debut");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval")
                        .HasColumnName("heure_fin");

                    b.Property<int?>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("id_club");

                    b.Property<int>("IdSalle")
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motif");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("statut");

                    b.HasKey("IdReservation");

                    b.HasIndex("IdClub");

                    b.HasIndex("IdSalle");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("reservations_salle", t =>
                        {
                            t.HasCheckConstraint("CK_Reservation_Statut", "statut IN ('en_attente','validee','annulee')");
                        });
                });

            modelBuilder.Entity("GESTION_S_E.Models.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_salle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSalle"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer")
                        .HasColumnName("capacite");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("localisation");

                    b.Property<string>("NomSalle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_salle");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("IdSalle");

                    b.HasIndex("NomSalle")
                        .IsUnique();

                    b.ToTable("salles", t =>
                        {
                            t.HasCheckConstraint("CK_Salle_Type", "\"type\" IN ('TP','cours','amphi','reunion')");
                        });
                });

            modelBuilder.Entity("GESTION_S_E.Models.Scolarite", b =>
                {
                    b.Property<int>("IdScolarite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_scolarite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdScolarite"));

                    b.Property<string>("Bureau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bureau");

                    b.Property<string>("Fonction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fonction");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("NomScolarite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_scolarite");

                    b.Property<string>("PrenomScolarite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom_scolarite");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdScolarite");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("scolarites");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("utilisateurs");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Club", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Utilisateur", "Responsable")
                        .WithMany()
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("GESTION_S_E.Models.DisponibiliteEnseignant", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Eleve", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Classe", "Classe")
                        .WithMany("Eleves")
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GESTION_S_E.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GESTION_S_E.Models.EleveGroupe", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Eleve", "Eleve")
                        .WithMany()
                        .HasForeignKey("IdEleve")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GESTION_S_E.Models.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("IdGroupe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("GESTION_S_E.Models.EmploiDuTemps", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Classe", "Classe")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("IdClasse");

                    b.HasOne("GESTION_S_E.Models.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GESTION_S_E.Models.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("IdGroupe");

                    b.HasOne("GESTION_S_E.Models.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GESTION_S_E.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("IdSalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Enseignant");

                    b.Navigation("Groupe");

                    b.Navigation("Matiere");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Enseignant", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Groupe", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Classe", "Classe")
                        .WithMany("Groupes")
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("GESTION_S_E.Models.MatiereClasse", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Classe", "Classe")
                        .WithMany("MatiereClasses")
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GESTION_S_E.Models.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("GESTION_S_E.Models.MembreClub", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GESTION_S_E.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Notification", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GESTION_S_E.Models.ReservationSalle", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("IdClub");

                    b.HasOne("GESTION_S_E.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("IdSalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GESTION_S_E.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Salle");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Scolarite", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Classe", b =>
                {
                    b.Navigation("Eleves");

                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Groupes");

                    b.Navigation("MatiereClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
