// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetAsp.Models;

#nullable disable

namespace GESTION_S_E.Migrations
{
    [DbContext(typeof(MonDbContext))]
    [Migration("20260509151020_AjoutTableEleveGroupe")]
    partial class AjoutTableEleveGroupe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GESTION_S_E.Models.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClasse"));

                    b.Property<string>("AnneeAcademique")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("annee_academique");

                    b.Property<int>("Effectif")
                        .HasColumnType("integer");

                    b.Property<string>("Filiere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NomClasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_classe");

                    b.HasKey("IdClasse");

                    b.ToTable("classes", t =>
                        {
                            t.HasCheckConstraint("CK_Classe_Niveau", "\"Niveau\" IN ('L1','L2','L3','M1','M2')");
                        });
                });

            modelBuilder.Entity("GESTION_S_E.Models.Eleve", b =>
                {
                    b.Property<int>("IdEleve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_eleve");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEleve"));

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_naissance");

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricule");

                    b.Property<string>("NomEleve")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_eleve");

                    b.Property<string>("PrenomEleve")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom_eleve");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdEleve");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("eleves");
                });

            modelBuilder.Entity("GESTION_S_E.Models.EleveGroupe", b =>
                {
                    b.Property<int>("IdEleve")
                        .HasColumnType("integer")
                        .HasColumnName("id_eleve");

                    b.Property<int>("IdGroupe")
                        .HasColumnType("integer")
                        .HasColumnName("id_groupe");

                    b.HasKey("IdEleve", "IdGroupe");

                    b.HasIndex("IdGroupe");

                    b.ToTable("eleve_groupe");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Enseignant", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_enseignant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnseignant"));

                    b.Property<string>("EmailPro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email_pro");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("NomEnseignant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_enseignant");

                    b.Property<string>("PrenomEnseignant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom_enseignant");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("specialite");

                    b.Property<string>("TelephoneEnseignant")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone_enseignant");

                    b.HasKey("IdEnseignant");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("enseignants");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Groupe", b =>
                {
                    b.Property<int>("IdGroupe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_groupe");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGroupe"));

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer")
                        .HasColumnName("id_classe");

                    b.Property<string>("NomGroupe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_groupe");

                    b.HasKey("IdGroupe");

                    b.HasIndex("IdClasse");

                    b.ToTable("groupes");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Scolarite", b =>
                {
                    b.Property<int>("IdScolarite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_scolarite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdScolarite"));

                    b.Property<string>("Bureau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bureau");

                    b.Property<string>("Fonction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fonction");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("NomScolarite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_scolarite");

                    b.Property<string>("PrenomScolarite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom_scolarite");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdScolarite");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("scolarites");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("utilisateurs");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Eleve", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GESTION_S_E.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GESTION_S_E.Models.EleveGroupe", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Eleve", "Eleve")
                        .WithMany()
                        .HasForeignKey("IdEleve")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GESTION_S_E.Models.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("IdGroupe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Enseignant", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Groupe", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Classe", "Classe")
                        .WithMany("Groupes")
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Scolarite", b =>
                {
                    b.HasOne("GESTION_S_E.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GESTION_S_E.Models.Classe", b =>
                {
                    b.Navigation("Groupes");
                });
#pragma warning restore 612, 618
        }
    }
}
